name: Build and Deploy CV

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pelican[markdown]
        pip install ghp-import

    - name: Build the site
      run: pelican content  # Здесь происходит сборка сайта из содержимого папки content

    - name: Deploy to GitHub Pages
      run: |
        ghp-import output  # Публикация файлов, собранных в папке output
        git push --force --quiet "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" gh-pages
